apiVersion: apps/v1
kind: Deployment
metadata:
  name: ponger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ponger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ponger
    spec:
      containers:
      - name: ponger
        image: library/ponger:latest
        imagePullPolicy: Never # required for k3d imported images
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ponger
spec:
  selector:
    app.kubernetes.io/name: ponger  # has changed pong to ponger to match the labels in deployment 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    #- name: http
      #port: 8080
      #protocol: TCP
      #targetPort: 8080
    #- name: https 
      #port: 443
      #protocol: TCP
      #targetPort: 8080

---

#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
  #name: default-deny-all
  #namespace: default
#spec:
  #podSelector: {}
  #policyTypes:
  #- Ingress
  #- Egress
---

#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
  #name: allow-allpods-to-dns
  #namespace: default
#spec:
  #policyTypes:
  #- Egress
  #podSelector: {}
  #egress:
  #- to:
    #- namespaceSelector:
        #matchLabels:
          #kubernetes.io/metadata.name: kube-system
      #podSelector:
        #matchLabels:
          #k8s-app: kube-dns
    #ports:
    #- port: 53
      #protocol: TCP
